# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fca170822c958c992a5effbfcc7dbb9782bf4a8370c456c58699790c03174bb8f8f2a850dff7f8e97e4f0ce644d08d5abb774e862c178c632c24039703454eb

test:
  secret_key_base: fa13df930ef461cc4054183d1db9b314951daef637a8595425d5242998d332c5e2c362e525dde113ca955334f224f26fda3d1b84166ea7c9d9d4508e5c01a9d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
